"""forum attachments

Revision ID: 2e5220fede24
Revises: 436e26b6cb7b
Create Date: 2026-08-10 11:57:31.961720

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e5220fede24'
down_revision: str | Sequence[str] | None = '436e26b6cb7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_key', sa.String(length=256), nullable=False),
    sa.Column('display_key', sa.String(length=256), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=256), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (post_id IS NOT NULL AND comment_id IS NOT NULL)', name='ck_attachments_single_owner'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_comment_id', 'attachments', ['comment_id'], unique=False)
    op.create_index('ix_attachments_post_id', 'attachments', ['post_id'], unique=False)
    op.create_index('ix_attachments_user_created', 'attachments', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_attachments_user_id'), 'attachments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_user_id'), table_name='attachments')
    op.drop_index('ix_attachments_user_created', table_name='attachments')
    op.drop_index('ix_attachments_post_id', table_name='attachments')
    op.drop_index('ix_attachments_comment_id', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
