"""pagination indexes + forum cascade

Revision ID: 436e26b6cb7b
Revises: 8e43b72a92a6
Create Date: 2026-08-09 17:59:37.067389

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '436e26b6cb7b'
down_revision: str | Sequence[str] | None = '8e43b72a92a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.create_index('ix_comments_post_created_id', 'comments', ['post_id', 'created_at', 'id'], unique=False)
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(
        'comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(op.f('likes_post_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(
        'likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'],
        ondelete='CASCADE',
    )
    op.create_index('ix_posts_created_id', 'posts', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_created_id', table_name='posts')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_post_id_fkey'), 'likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    op.drop_index('ix_comments_post_created_id', table_name='comments')
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    # ### end Alembic commands ###
