"""drop posts.category

Revision ID: 684168b30deb
Revises: 3552371b2153
Create Date: 2026-08-14 20:09:08.836161

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '684168b30deb'
down_revision: str | Sequence[str] | None = '3552371b2153'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
