"""rate_limits table

Revision ID: a3190b9b6c64
Revises: 2e5220fede24
Create Date: 2026-08-13 12:21:28.742321

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a3190b9b6c64'
down_revision: str | Sequence[str] | None = '2e5220fede24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bucket')
    )
    op.create_index(op.f('ix_rate_limits_expires_at'), 'rate_limits', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limits_expires_at'), table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
